import React from 'react';
import Link from 'next/link';
import type { Metadata } from 'next';
import { SiteHeader } from '@/components/site-header';
import {
  BookOpen,
  Cpu,
  Layers,
  Sparkles,
  ExternalLink,
  Heart,
  Globe,
  Workflow,
  CheckCircle2,
  Code2,
  Terminal,
  Library,
  Compass,
} from 'lucide-react';

function GithubIcon({ className = 'w-4 h-4' }: { className?: string }) {
  return (
    <svg
      className={className}
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
      aria-hidden="true"
    >
      <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
      <path d="M9 18c-4.51 2-5-2-7-2" />
    </svg>
  );
}

export const metadata: Metadata = {
  title: 'About Omni Archivist — Autonomous Deep-Time Speculative Anthology',
  description:
    'The architectural design, narratological algorithms, daily generation pipeline, and technical stack behind Omni Archivist.',
};

export default function AboutPage() {
  return (
    <>
      <SiteHeader />

      <main className="max-w-5xl mx-auto px-4 sm:px-6 py-10 sm:py-16 space-y-16">
        {/* Hero Section */}
        <section className="p-8 sm:p-14 rounded-3xl bg-card border border-border shadow-2xl relative overflow-hidden">
          <div className="absolute top-0 left-0 right-0 h-[3px] bg-gradient-to-r from-[#bb3e03] via-[#ee9b00] to-[#0a9396]" />

          <div className="max-w-3xl space-y-6">
            <span className="inline-block font-display text-xs sm:text-sm font-bold tracking-widest text-[#bb3e03] dark:text-[#ee9b00] uppercase px-3.5 py-1 rounded-full bg-[#bb3e03]/10 dark:bg-[#ee9b00]/15 border border-[#bb3e03]/25 dark:border-[#ee9b00]/30 shadow-sm">
              ARCHIVAL ARCHITECTURE &amp; MANIFESTO
            </span>

            <h1 className="font-brand font-black text-3xl sm:text-5xl tracking-tight bg-gradient-to-r from-[#001219] via-[#005f73] to-[#bb3e03] dark:from-white dark:via-[#e9d8a6] dark:to-[#ee9b00] bg-clip-text text-transparent">
              About Omni Archivist
            </h1>

            <p className="font-prose italic text-lg sm:text-xl text-[#bb3e03] dark:text-[#ee9b00] leading-snug font-medium">
              An autonomous speculative intelligence chronicling humanity&apos;s infinite horizons across deep time, synthesized under the Human Era calendar.
            </p>

            <div className="font-prose text-base sm:text-lg text-foreground/90 space-y-4 leading-relaxed pt-2">
              <p>
                <strong>Omni Archivist</strong> is an autonomous collection of speculative fiction short stories generated by Google Gemini AI and curated and architected by{' '}
                <a
                  href="https://raitucarp.name"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="font-semibold text-[#bb3e03] dark:text-[#ee9b00] underline decoration-[#bb3e03]/40 hover:decoration-[#bb3e03] transition-colors"
                >
                  Ribhararnus Pracutiar
                </a>
                . The project explores the intersection of computational creativity, formal narratological theory, and computational linguistics.
              </p>
              <p>
                Rather than treating generative large language models as unguided prose generators, Omni Archivist implements a structured multi-phase pipeline governed by strict literary criteria, narratological algorithms, and lexical enrichment powered by{' '}
                <a
                  href="https://github.com/raitucarp/gown"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="font-semibold text-[#005f73] dark:text-[#94d2bd] underline decoration-[#005f73]/40 hover:decoration-[#005f73] transition-colors"
                >
                  gown
                </a>
                —a custom Go WordNet library authored by Ribhararnus.
              </p>
              <p>
                The anthology is anchored to the <strong>Human Era (12026 HE)</strong> calendar, marking twelve millennia since humanity first erected monumental architecture and mapped sidereal constellations, extending our collective civilizational trajectory into deep time.
              </p>
            </div>

            {/* Quick Links / Badges */}
            <div className="flex flex-wrap items-center gap-3 pt-4">
              <a
                href="https://ko-fi.com/raitucarp"
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-2 px-4 py-2 rounded-xl bg-[#bb3e03] text-white hover:bg-[#a03402] dark:bg-[#ee9b00] dark:text-[#001219] font-bold text-sm shadow-md transition-all hover:scale-105"
              >
                <Heart className="w-4 h-4 fill-current" />
                <span>Support on Ko-fi</span>
              </a>
              <a
                href="https://github.com/raitucarp"
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-2 px-4 py-2 rounded-xl bg-card border border-border hover:bg-muted text-foreground text-sm font-semibold transition-colors"
              >
                <GithubIcon className="w-4 h-4" />
                <span>GitHub @raitucarp</span>
              </a>
              <a
                href="https://raitucarp.name"
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-2 px-4 py-2 rounded-xl bg-card border border-border hover:bg-muted text-foreground text-sm font-semibold transition-colors"
              >
                <Globe className="w-4 h-4" />
                <span>raitucarp.name</span>
              </a>
            </div>
          </div>
        </section>

        {/* Daily Generation Pipeline */}
        <section className="space-y-8">
          <div className="space-y-2">
            <div className="flex items-center gap-2 text-xs font-mono font-bold tracking-widest text-[#005f73] dark:text-[#94d2bd] uppercase">
              <Workflow className="w-4 h-4" />
              <span>Solar Cycle Execution</span>
            </div>
            <h2 className="font-display font-bold text-2xl sm:text-4xl text-foreground">
              Daily Story Generation Pipeline
            </h2>
            <p className="font-prose text-base sm:text-lg text-muted-foreground leading-relaxed">
              Every story transmission is generated through an automated, multi-phase Go CLI workflow executed on a scheduled GitHub Actions cron job. Each phase is an autonomous step that verifies, crafts, and enriches narrative metadata.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="p-6 rounded-2xl bg-card border border-border space-y-3 shadow-sm hover:border-[#ee9b00]/50 transition-colors">
              <div className="flex items-center gap-3">
                <span className="flex items-center justify-center w-8 h-8 rounded-lg bg-[#ee9b00]/15 text-[#bb3e03] dark:text-[#ee9b00] font-mono font-bold text-sm">
                  01
                </span>
                <h3 className="font-display font-bold text-lg text-foreground">
                  Artifacts &amp; Health Check
                </h3>
              </div>
              <p className="font-prose text-sm text-foreground/80 leading-relaxed">
                Command: <code className="font-mono text-xs px-1.5 py-0.5 rounded bg-muted">omni-archivist check artifacts</code>. Validates workspace integrity, detects previous runs for idempotency, and initializes the temporal directory structure under <code className="font-mono text-xs px-1.5 py-0.5 rounded bg-muted">artifacts/YYYY/MM/DD/</code>.
              </p>
            </div>

            <div className="p-6 rounded-2xl bg-card border border-border space-y-3 shadow-sm hover:border-[#ee9b00]/50 transition-colors">
              <div className="flex items-center gap-3">
                <span className="flex items-center justify-center w-8 h-8 rounded-lg bg-[#ee9b00]/15 text-[#bb3e03] dark:text-[#ee9b00] font-mono font-bold text-sm">
                  02
                </span>
                <h3 className="font-display font-bold text-lg text-foreground">
                  Science Field &amp; Sci-Fi Genre Selection
                </h3>
              </div>
              <p className="font-prose text-sm text-foreground/80 leading-relaxed">
                Commands: <code className="font-mono text-xs px-1.5 py-0.5 rounded bg-muted">pick science_field</code> and <code className="font-mono text-xs px-1.5 py-0.5 rounded bg-muted">pick scifi_genre</code>. Randomly selects and couples a specialized scientific discipline (astrophysics, synthetic biology, xenolinguistics, cognitive cybernetics) with an evocative speculative genre (cyberpunk, hard sci-fi, solarpunk, cosmic horror, time-dilation drama).
              </p>
            </div>

            <div className="p-6 rounded-2xl bg-card border border-border space-y-3 shadow-sm hover:border-[#0a9396]/50 transition-colors md:col-span-2">
              <div className="flex items-center gap-3">
                <span className="flex items-center justify-center w-8 h-8 rounded-lg bg-[#0a9396]/15 text-[#005f73] dark:text-[#94d2bd] font-mono font-bold text-sm">
                  03
                </span>
                <h3 className="font-display font-bold text-lg text-foreground">
                  Lexical Seeding via gown (WordNet in Go)
                </h3>
              </div>
              <p className="font-prose text-sm text-foreground/80 leading-relaxed">
                Command: <code className="font-mono text-xs px-1.5 py-0.5 rounded bg-muted">pick vocabs_composition</code>. The system queries Gemini to choose target lexical categories based on the selected science and genre, then queries <a href="https://github.com/raitucarp/gown" target="_blank" rel="noopener noreferrer" className="font-bold underline text-[#005f73] dark:text-[#94d2bd]">gown</a>—Ribhararnus&apos;s pure-Go WordNet library. gown samples exact lemmas, synsets, and definitions across nouns, verbs, adjectives, and adverbs. This prevents stereotypical LLM prose clichés by seeding rare, evocative, and semantically grounded terminology directly into the story prompts.
              </p>
            </div>

            <div className="p-6 rounded-2xl bg-card border border-border space-y-3 shadow-sm hover:border-[#ee9b00]/50 transition-colors">
              <div className="flex items-center gap-3">
                <span className="flex items-center justify-center w-8 h-8 rounded-lg bg-[#ee9b00]/15 text-[#bb3e03] dark:text-[#ee9b00] font-mono font-bold text-sm">
                  04
                </span>
                <h3 className="font-display font-bold text-lg text-foreground">
                  Premise, Synopsis &amp; Theme
                </h3>
              </div>
              <p className="font-prose text-sm text-foreground/80 leading-relaxed">
                Command: <code className="font-mono text-xs px-1.5 py-0.5 rounded bg-muted">write synopsis</code>. Formulates the core premise, thematic inquiry, title, subtitle, blurb, and a concise logline combining the science, genre, and vocabulary constraints.
              </p>
            </div>

            <div className="p-6 rounded-2xl bg-card border border-border space-y-3 shadow-sm hover:border-[#ee9b00]/50 transition-colors">
              <div className="flex items-center gap-3">
                <span className="flex items-center justify-center w-8 h-8 rounded-lg bg-[#ee9b00]/15 text-[#bb3e03] dark:text-[#ee9b00] font-mono font-bold text-sm">
                  05
                </span>
                <h3 className="font-display font-bold text-lg text-foreground">
                  Worldbuilding &amp; Spatial Existents
                </h3>
              </div>
              <p className="font-prose text-sm text-foreground/80 leading-relaxed">
                Command: <code className="font-mono text-xs px-1.5 py-0.5 rounded bg-muted">write setting</code>. Constructs three nested tiers of setting: <em>Macro</em> (planetary/system level), <em>Meso</em> (habitats, stations, architectural structures), and <em>Micro</em> (immediate sensory, tactile, and atmospheric details).
              </p>
            </div>

            <div className="p-6 rounded-2xl bg-card border border-border space-y-3 shadow-sm hover:border-[#ee9b00]/50 transition-colors">
              <div className="flex items-center gap-3">
                <span className="flex items-center justify-center w-8 h-8 rounded-lg bg-[#ee9b00]/15 text-[#bb3e03] dark:text-[#ee9b00] font-mono font-bold text-sm">
                  06
                </span>
                <h3 className="font-display font-bold text-lg text-foreground">
                  Character Conception &amp; Psychological Drives
                </h3>
              </div>
              <p className="font-prose text-sm text-foreground/80 leading-relaxed">
                Command: <code className="font-mono text-xs px-1.5 py-0.5 rounded bg-muted">write characters</code>. Defines POV protagonists and foils with internal stakes, external dilemmas, fatal flaws, and psychological arcs grounded in the story&apos;s speculative environment.
              </p>
            </div>

            <div className="p-6 rounded-2xl bg-card border border-border space-y-3 shadow-sm hover:border-[#ee9b00]/50 transition-colors">
              <div className="flex items-center gap-3">
                <span className="flex items-center justify-center w-8 h-8 rounded-lg bg-[#ee9b00]/15 text-[#bb3e03] dark:text-[#ee9b00] font-mono font-bold text-sm">
                  07
                </span>
                <h3 className="font-display font-bold text-lg text-foreground">
                  MICE Structure &amp; Scene-Sequel Blueprint
                </h3>
              </div>
              <p className="font-prose text-sm text-foreground/80 leading-relaxed">
                Commands: <code className="font-mono text-xs px-1.5 py-0.5 rounded bg-muted">write structure</code> &amp; <code className="font-mono text-xs px-1.5 py-0.5 rounded bg-muted">write scene_structures</code>. Establishes narrative logic using Orson Scott Card&apos;s MICE quotient and Dwight V. Swain&apos;s Scene &amp; Sequel units (Goal &rarr; Conflict &rarr; Disaster &rarr; Reaction &rarr; Dilemma &rarr; Decision).
              </p>
            </div>

            <div className="p-6 rounded-2xl bg-card border border-border space-y-3 shadow-sm hover:border-[#ee9b00]/50 transition-colors">
              <div className="flex items-center gap-3">
                <span className="flex items-center justify-center w-8 h-8 rounded-lg bg-[#ee9b00]/15 text-[#bb3e03] dark:text-[#ee9b00] font-mono font-bold text-sm">
                  08
                </span>
                <h3 className="font-display font-bold text-lg text-foreground">
                  Drafting Prose &amp; Narratological Rewrite
                </h3>
              </div>
              <p className="font-prose text-sm text-foreground/80 leading-relaxed">
                Commands: <code className="font-mono text-xs px-1.5 py-0.5 rounded bg-muted">write story</code> followed by <code className="font-mono text-xs px-1.5 py-0.5 rounded bg-muted">write rewrite</code>. A full raw draft (<code className="font-mono text-xs px-1 py-0.5 rounded bg-muted">draft.md</code>) is written first. Then, a specialized rewrite pass audits the text against Genette&apos;s narrative discourse principles, refining cadence, sensory immersion, and eliminating passive exposition.
              </p>
            </div>

            <div className="p-6 rounded-2xl bg-card border border-border space-y-3 shadow-sm hover:border-[#0a9396]/50 transition-colors md:col-span-2">
              <div className="flex items-center gap-3">
                <span className="flex items-center justify-center w-8 h-8 rounded-lg bg-[#0a9396]/15 text-[#005f73] dark:text-[#94d2bd] font-mono font-bold text-sm">
                  09
                </span>
                <h3 className="font-display font-bold text-lg text-foreground">
                  Visual Aesthetic Matrix &amp; Cover Art Generation
                </h3>
              </div>
              <p className="font-prose text-sm text-foreground/80 leading-relaxed">
                Command: <code className="font-mono text-xs px-1.5 py-0.5 rounded bg-muted">write cover</code>. The system constructs an aesthetic vector combining randomized art mediums, photographic lenses, lighting scenarios, and color palettes, generating an evocative cover illustration using Gemini Flash Image / Imagen 3.
              </p>
            </div>
          </div>
        </section>

        {/* Narratological Algorithms & Theoretical Framework */}
        <section className="p-8 sm:p-12 rounded-3xl bg-card border border-border shadow-xl space-y-8">
          <div className="space-y-2">
            <div className="flex items-center gap-2 text-xs font-mono font-bold tracking-widest text-[#bb3e03] dark:text-[#ee9b00] uppercase">
              <Library className="w-4 h-4" />
              <span>Literary Algorithms &amp; Theoretical Framework</span>
            </div>
            <h2 className="font-display font-bold text-2xl sm:text-3xl text-foreground">
              Algorithmic Narratology
            </h2>
            <p className="font-prose text-base text-muted-foreground leading-relaxed">
              Omni Archivist formalizes established literary theory and structural narratology into computable Go data models and Gemini prompt schemas:
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            <div className="space-y-3">
              <h3 className="font-display font-bold text-xl text-foreground flex items-center gap-2">
                <Compass className="w-5 h-5 text-[#ee9b00]" />
                <span>The MICE Quotient</span>
              </h3>
              <p className="font-prose text-sm text-foreground/80 leading-relaxed">
                Based on Orson Scott Card&apos;s structural taxonomy, stories are organized as nested narrative promises opened and closed systematically:
              </p>
              <ul className="text-xs font-mono space-y-1.5 text-muted-foreground pl-2 border-l-2 border-[#ee9b00]/40">
                <li><strong className="text-foreground">Milieu (MO/MC):</strong> Opening with arrival into an unfamiliar universe, concluding with departure or integration.</li>
                <li><strong className="text-foreground">Inquiry (IO/IC):</strong> Opening with a riddle or scientific anomaly, concluding with revelation or irreversible truth.</li>
                <li><strong className="text-foreground">Character (CO/CC):</strong> Opening with internal dissatisfaction, concluding with transformed self-conception.</li>
                <li><strong className="text-foreground">Event (EO/EC):</strong> Opening with cosmic or system disequilibrium, concluding with new order or catastrophe.</li>
              </ul>
            </div>

            <div className="space-y-3">
              <h3 className="font-display font-bold text-xl text-foreground flex items-center gap-2">
                <Layers className="w-5 h-5 text-[#0a9396]" />
                <span>Swain&apos;s Scene &amp; Sequel Engine</span>
              </h3>
              <p className="font-prose text-sm text-foreground/80 leading-relaxed">
                Derived from Dwight V. Swain&apos;s narratology, pacing is guaranteed through tightly linked cause-and-effect units:
              </p>
              <ul className="text-xs font-mono space-y-1.5 text-muted-foreground pl-2 border-l-2 border-[#0a9396]/40">
                <li><strong className="text-foreground">Scene (Action):</strong> Goal (immediate desire) &rarr; Conflict (person, environment, system, or self resistance) &rarr; Disaster (unanticipated setback).</li>
                <li><strong className="text-foreground">Sequel (Reaction):</strong> Emotional/visceral reaction &rarr; Dilemma (impossible choices with tangible risks) &rarr; Decision &amp; New Goal.</li>
              </ul>
            </div>

            <div className="space-y-3">
              <h3 className="font-display font-bold text-xl text-foreground flex items-center gap-2">
                <BookOpen className="w-5 h-5 text-[#bb3e03] dark:text-[#ee9b00]" />
                <span>Genette&apos;s Narrative Discourse</span>
              </h3>
              <p className="font-prose text-sm text-foreground/80 leading-relaxed">
                Implements Gérard Genette&apos;s structural narratology:
              </p>
              <ul className="text-xs font-mono space-y-1 text-muted-foreground pl-2 border-l-2 border-[#bb3e03]/40">
                <li><strong>Voice:</strong> Autodiegetic, homodiegetic, heterodiegetic perspectives.</li>
                <li><strong>Level:</strong> Extradiegetic vs. intradiegetic framing.</li>
                <li><strong>Focalisation:</strong> Zero (omniscient), internal (fixed or variable), external (objective).</li>
                <li><strong>Reliability:</strong> Calibrated narrative veracity.</li>
              </ul>
            </div>

            <div className="space-y-3">
              <h3 className="font-display font-bold text-xl text-foreground flex items-center gap-2">
                <Sparkles className="w-5 h-5 text-[#005f73] dark:text-[#94d2bd]" />
                <span>gown WordNet Lexical Infusion</span>
              </h3>
              <p className="font-prose text-sm text-foreground/80 leading-relaxed">
                Utilizes <a href="https://github.com/raitucarp/gown" target="_blank" rel="noopener noreferrer" className="font-bold underline text-[#005f73] dark:text-[#94d2bd]">gown</a> to programmatically extract lexical synsets from Princeton WordNet data files. This enforces semantic richness, introduces precise terminology from scientific domains, and prevents the repetitive lexical habits common in large language models.
              </p>
            </div>
          </div>
        </section>

        {/* Weekly Compilation & EPUB Generation */}
        <section className="p-8 sm:p-12 rounded-3xl bg-card border border-border shadow-xl space-y-8">
          <div className="space-y-2">
            <div className="flex items-center gap-2 text-xs font-mono font-bold tracking-widest text-[#005f73] dark:text-[#94d2bd] uppercase">
              <BookOpen className="w-4 h-4" />
              <span>Weekly Compilation &amp; E-Book Publishing</span>
            </div>
            <h2 className="font-display font-bold text-2xl sm:text-3xl text-foreground">
              Autonomous Weekly Omnibus Compilation
            </h2>
            <p className="font-prose text-base text-muted-foreground leading-relaxed">
              Every Sunday at 00:00 UTC, a dedicated compilation workflow (<code className="font-mono text-xs px-1.5 py-0.5 rounded bg-muted">weekly_epub.yml</code>) aggregates all stories published during the week into an archival omnibus volume.
            </p>
          </div>

          <div className="space-y-6">
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
              <div className="p-5 rounded-2xl bg-muted/40 border border-border/80 space-y-2">
                <div className="text-xs font-mono text-muted-foreground uppercase font-bold">1. Chronological Aggregation</div>
                <p className="font-prose text-sm text-foreground/85">
                  Walks the repository&apos;s <code className="font-mono text-xs">artifacts/</code> folder, parsing YAML metadata dossiers, story prose, and cover imagery for each transmission in the current weekly cycle.
                </p>
              </div>

              <div className="p-5 rounded-2xl bg-muted/40 border border-border/80 space-y-2">
                <div className="text-xs font-mono text-muted-foreground uppercase font-bold">2. Curatorial AI Preface</div>
                <p className="font-prose text-sm text-foreground/85">
                  Gemini analyzes the themes, genres, scientific fields, and loglines across all stories in the volume to compose an overarching <em>Curatorial Overview Essay</em> and a thematic synthesis subtitle.
                </p>
              </div>

              <div className="p-5 rounded-2xl bg-muted/40 border border-border/80 space-y-2">
                <div className="text-xs font-mono text-muted-foreground uppercase font-bold">3. EPUB 3 Packaging with epub</div>
                <p className="font-prose text-sm text-foreground/85">
                  Leverages <a href="https://github.com/raitucarp/epub" target="_blank" rel="noopener noreferrer" className="font-bold underline text-[#005f73] dark:text-[#94d2bd]">github.com/raitucarp/epub</a>—Ribhararnus&apos;s custom Go EPUB library—to bundle the chapters, table of contents, cover art, and metadata into a valid standard EPUB file.
                </p>
              </div>
            </div>

            <div className="p-4 rounded-xl bg-card border border-border text-sm font-mono text-muted-foreground flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
              <div className="flex items-center gap-2">
                <Terminal className="w-4 h-4 text-[#ee9b00]" />
                <span>Compilation Command:</span>
                <code className="text-foreground font-semibold">./omni-archivist compile epub --dir artifacts --output omni-archivist-12026-w37.epub</code>
              </div>
              <span className="text-xs px-2.5 py-1 rounded bg-[#0a9396]/15 text-[#005f73] dark:text-[#94d2bd] font-bold">
                Automated Release via GitHub Actions
              </span>
            </div>
          </div>
        </section>

        {/* Technical Architecture & Stack */}
        <section className="space-y-8">
          <div className="space-y-2">
            <div className="flex items-center gap-2 text-xs font-mono font-bold tracking-widest text-[#bb3e03] dark:text-[#ee9b00] uppercase">
              <Cpu className="w-4 h-4" />
              <span>Full Technical Specifications</span>
            </div>
            <h2 className="font-display font-bold text-2xl sm:text-4xl text-foreground">
              The Technology Stack
            </h2>
            <p className="font-prose text-base sm:text-lg text-muted-foreground leading-relaxed">
              Engineered with modern systems programming and web standards:
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {/* Go CLI & Engine */}
            <div className="p-6 rounded-2xl bg-card border border-border space-y-4">
              <div className="flex items-center gap-3">
                <div className="p-2.5 rounded-xl bg-[#005f73]/10 text-[#005f73] dark:text-[#94d2bd]">
                  <Code2 className="w-6 h-6" />
                </div>
                <div>
                  <h3 className="font-display font-bold text-lg text-foreground">
                    Go Core Generation Engine
                  </h3>
                  <p className="text-xs font-mono text-muted-foreground">Backend &amp; CLI</p>
                </div>
              </div>

              <ul className="font-prose text-sm text-foreground/80 space-y-2">
                <li className="flex items-start gap-2">
                  <CheckCircle2 className="w-4 h-4 text-[#ee9b00] shrink-0 mt-0.5" />
                  <span><strong>Go (Golang 1.25+ / 1.26):</strong> Robust, typed CLI binary orchestrating all generation phases.</span>
                </li>
                <li className="flex items-start gap-2">
                  <CheckCircle2 className="w-4 h-4 text-[#ee9b00] shrink-0 mt-0.5" />
                  <span><strong>Firebase Genkit for Go (<code className="font-mono text-xs">github.com/firebase/genkit/go</code>):</strong> Schema validation, structured JSON outputs, and Google GenAI plugin integration.</span>
                </li>
                <li className="flex items-start gap-2">
                  <CheckCircle2 className="w-4 h-4 text-[#ee9b00] shrink-0 mt-0.5" />
                  <span><strong>Google Gemini (<code className="font-mono text-xs">gemini-2.5-flash</code> / <code className="font-mono text-xs">gemini-3.1-flash-image</code> / Imagen 3):</strong> Advanced language reasoning and cover image generation.</span>
                </li>
                <li className="flex items-start gap-2">
                  <CheckCircle2 className="w-4 h-4 text-[#ee9b00] shrink-0 mt-0.5" />
                  <span><strong>gown (<code className="font-mono text-xs">github.com/raitucarp/gown</code>):</strong> Ribhararnus&apos;s native Go library for Princeton WordNet semantic traversal and vocabulary sampling.</span>
                </li>
                <li className="flex items-start gap-2">
                  <CheckCircle2 className="w-4 h-4 text-[#ee9b00] shrink-0 mt-0.5" />
                  <span><strong>epub (<code className="font-mono text-xs">github.com/raitucarp/epub</code>):</strong> Native Go EPUB 3 packager and builder.</span>
                </li>
                <li className="flex items-start gap-2">
                  <CheckCircle2 className="w-4 h-4 text-[#ee9b00] shrink-0 mt-0.5" />
                  <span><strong>urfave/cli/v3 &amp; retry-go/v5:</strong> Expressive CLI subcommands with resilient exponential-backoff retries.</span>
                </li>
              </ul>
            </div>

            {/* Web Frontend & Reader */}
            <div className="p-6 rounded-2xl bg-card border border-border space-y-4">
              <div className="flex items-center gap-3">
                <div className="p-2.5 rounded-xl bg-[#bb3e03]/10 text-[#bb3e03] dark:text-[#ee9b00]">
                  <Globe className="w-6 h-6" />
                </div>
                <div>
                  <h3 className="font-display font-bold text-lg text-foreground">
                    Web Reader &amp; Static Site
                  </h3>
                  <p className="text-xs font-mono text-muted-foreground">Frontend &amp; UX</p>
                </div>
              </div>

              <ul className="font-prose text-sm text-foreground/80 space-y-2">
                <li className="flex items-start gap-2">
                  <CheckCircle2 className="w-4 h-4 text-[#0a9396] shrink-0 mt-0.5" />
                  <span><strong>Next.js 16 (App Router):</strong> Pre-rendered static export (<code className="font-mono text-xs">output: &apos;export&apos;</code>) for lightning-fast edge delivery.</span>
                </li>
                <li className="flex items-start gap-2">
                  <CheckCircle2 className="w-4 h-4 text-[#0a9396] shrink-0 mt-0.5" />
                  <span><strong>React 19 &amp; TypeScript:</strong> Type-safe UI components, interactive reading companion, and metadata dossier inspectors.</span>
                </li>
                <li className="flex items-start gap-2">
                  <CheckCircle2 className="w-4 h-4 text-[#0a9396] shrink-0 mt-0.5" />
                  <span><strong>Tailwind CSS v4:</strong> Atmospheric color palettes, custom editorial serif typography (Literata, Cormorant Garamond), and Syne/Space Grotesk display fonts.</span>
                </li>
                <li className="flex items-start gap-2">
                  <CheckCircle2 className="w-4 h-4 text-[#0a9396] shrink-0 mt-0.5" />
                  <span><strong>Theme Engine &amp; Focus Mode:</strong> Seamless dark/light theme switching with paragraph-level reading focus illumination.</span>
                </li>
                <li className="flex items-start gap-2">
                  <CheckCircle2 className="w-4 h-4 text-[#0a9396] shrink-0 mt-0.5" />
                  <span><strong>Lucide React:</strong> Clean, minimalist vector iconography.</span>
                </li>
                <li className="flex items-start gap-2">
                  <CheckCircle2 className="w-4 h-4 text-[#0a9396] shrink-0 mt-0.5" />
                  <span><strong>GitHub Pages:</strong> Deployed via GitHub Actions to custom domain <code className="font-mono text-xs">omni-archivist.raitucarp.name</code>.</span>
                </li>
              </ul>
            </div>
          </div>
        </section>

        {/* Creator & Support Section */}
        <section className="p-8 sm:p-12 rounded-3xl bg-card border border-border shadow-2xl relative overflow-hidden space-y-6">
          <div className="space-y-3">
            <span className="inline-block text-xs font-mono font-bold tracking-widest text-[#bb3e03] dark:text-[#ee9b00] uppercase">
              ARCHIVIST &amp; CURATOR
            </span>
            <h2 className="font-display font-black text-2xl sm:text-4xl text-foreground">
              Ribhararnus Pracutiar
            </h2>
            <p className="font-prose text-base sm:text-lg text-foreground/85 max-w-3xl leading-relaxed">
              Software engineer, open-source author, and narrative computationalist. Ribhararnus writes tools in Go, explores language models, and creates speculative artifacts that bridge literature, computational linguistics, and systems programming.
            </p>
          </div>

          <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-4 pt-2">
            <a
              href="https://ko-fi.com/raitucarp"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center justify-center gap-2 px-6 py-3.5 rounded-2xl bg-[#bb3e03] text-white hover:bg-[#a03402] dark:bg-[#ee9b00] dark:text-[#001219] font-bold text-base shadow-lg transition-all hover:scale-105"
            >
              <Heart className="w-5 h-5 fill-current" />
              <span>Support on Ko-fi</span>
            </a>

            <a
              href="https://github.com/raitucarp"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center justify-center gap-2 px-6 py-3.5 rounded-2xl bg-card border border-border hover:bg-muted text-foreground font-semibold text-base shadow-sm transition-colors"
            >
              <GithubIcon className="w-5 h-5" />
              <span>GitHub (@raitucarp)</span>
              <ExternalLink className="w-4 h-4 text-muted-foreground ml-1" />
            </a>

            <a
              href="https://raitucarp.name"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center justify-center gap-2 px-6 py-3.5 rounded-2xl bg-card border border-border hover:bg-muted text-foreground font-semibold text-base shadow-sm transition-colors"
            >
              <Globe className="w-5 h-5" />
              <span>Personal Site (raitucarp.name)</span>
              <ExternalLink className="w-4 h-4 text-muted-foreground ml-1" />
            </a>
          </div>
        </section>

        {/* Bottom Navigation */}
        <div className="pt-4 flex items-center justify-between border-t border-border/80 text-sm font-mono">
          <Link
            href="/"
            className="inline-flex items-center gap-2 text-muted-foreground hover:text-foreground transition-colors font-semibold"
          >
            <span>&larr; Back to Weekly Anthologies</span>
          </Link>

          <a
            href="https://github.com/raitucarp/omni-archivist"
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-1.5 text-muted-foreground hover:text-foreground transition-colors"
          >
            <span>View Source on GitHub</span>
            <ExternalLink className="w-3.5 h-3.5" />
          </a>
        </div>
      </main>
    </>
  );
}
