package metadata

type ScienceField struct {
	Name        string `yaml:"name" json:"name" jsonschema:"description=The name of the scientific field, e.g., Physics, Biology"`
	Description string `yaml:"description" json:"description" jsonschema:"description=A brief description of the scientific field"`
}

type SciFiGenre struct {
	Name        string `yaml:"name" json:"name" jsonschema:"description=The name of the science fiction subgenre, e.g., Cyberpunk, Space Opera"`
	Description string `yaml:"description" json:"description" jsonschema:"description=A brief description of the science fiction subgenre"`
}

var ScienceFields = []ScienceField{
	{"Physics", "Study of matter, energy, space, time, and fundamental interactions"},
	{"Classical Mechanics", "Motion of bodies under forces"},
	{"Quantum Mechanics", "Physical behavior at atomic and subatomic scales"},
	{"Quantum Field Theory", "Quantum mechanics applied to fields"},
	{"Relativity", "Physics of spacetime and gravitation"},
	{"General Relativity", "Gravitational theory based on spacetime curvature"},
	{"Thermodynamics", "Heat, work, entropy, and energy transfer"},
	{"Statistical Mechanics", "Microscopic basis of thermodynamics"},
	{"Electromagnetism", "Electric and magnetic fields and forces"},
	{"Optics", "Behavior and properties of light"},
	{"Acoustics", "Study of sound and vibration"},
	{"Condensed Matter Physics", "Physical properties of solids and liquids"},
	{"Solid State Physics", "Crystalline and electronic properties of solids"},
	{"Plasma Physics", "Ionized gases and plasma behavior"},
	{"Nuclear Physics", "Atomic nuclei and nuclear reactions"},
	{"Particle Physics", "Fundamental particles and forces"},
	{"Astrophysics", "Physics of celestial objects"},
	{"Cosmology", "Origin and evolution of the universe"},
	{"Biophysics", "Application of physics to biological systems"},
	{"Geophysics", "Physics of the Earth"},
	{"Medical Physics", "Physics applied to medicine"},
	{"Computational Physics", "Numerical simulation of physical systems"},
	{"Chemistry", "Study of matter, composition, structure, and reactions"},
	{"Physical Chemistry", "Physical principles applied to chemical systems"},
	{"Organic Chemistry", "Chemistry of carbon-containing compounds"},
	{"Inorganic Chemistry", "Chemistry of non-organic compounds"},
	{"Analytical Chemistry", "Chemical analysis and measurement"},
	{"Biochemistry", "Chemical processes in living organisms"},
	{"Theoretical Chemistry", "Mathematical models of chemical systems"},
	{"Computational Chemistry", "Computer simulation of molecules"},
	{"Materials Chemistry", "Chemical design of materials"},
	{"Environmental Chemistry", "Chemical processes in the environment"},
	{"Atmospheric Chemistry", "Chemistry of the atmosphere"},
	{"Electrochemistry", "Chemical processes involving electricity"},
	{"Polymer Chemistry", "Macromolecules and polymers"},
	{"Nuclear Chemistry", "Chemical aspects of nuclear processes"},
	{"Medicinal Chemistry", "Chemical drug design"},
	{"Green Chemistry", "Sustainable chemical practices"},
	{"Astrochemistry", "Chemistry in space"},
	{"Biology", "Study of living organisms"},
	{"Molecular Biology", "Biological processes at molecular scale"},
	{"Cell Biology", "Structure and function of cells"},
	{"Genetics", "Heredity and genetic variation"},
	{"Epigenetics", "Heritable changes not encoded in DNA sequence"},
	{"Developmental Biology", "Growth and development of organisms"},
	{"Evolutionary Biology", "Origin and evolution of life"},
	{"Ecology", "Interactions between organisms and environment"},
	{"Microbiology", "Study of microorganisms"},
	{"Virology", "Viruses and viral diseases"},
	{"Bacteriology", "Bacteria"},
	{"Mycology", "Fungi"},
	{"Zoology", "Animals"},
	{"Botany", "Plants"},
	{"Physiology", "Functions of living systems"},
	{"Neuroscience", "Nervous systems"},
	{"Neurobiology", "Biology of neurons"},
	{"Immunology", "Immune systems"},
	{"Endocrinology", "Hormonal systems"},
	{"Systems Biology", "Biological systems as integrated networks"},
	{"Synthetic Biology", "Engineering biological systems"},
	{"Bioinformatics", "Computational analysis of biological data"},
	{"Biostatistics", "Statistics applied to biology"},
	{"Marine Biology", "Ocean life"},
	{"Conservation Biology", "Preservation of biodiversity"},
	{"Astrobiology", "Life beyond Earth"},
	{"Behavioral Biology", "Biological basis of behavior"},
	{"Earth Science", "Study of Earth systems"},
	{"Geology", "Solid Earth materials and processes"},
	{"Mineralogy", "Minerals"},
	{"Petrology", "Rocks"},
	{"Structural Geology", "Deformation of Earth materials"},
	{"Sedimentology", "Sedimentary rocks and processes"},
	{"Stratigraphy", "Layered rock formations"},
	{"Paleontology", "Fossils and ancient life"},
	{"Seismology", "Earthquakes"},
	{"Volcanology", "Volcanoes"},
	{"Geochemistry", "Chemical composition of Earth"},
	{"Geochronology", "Dating geological events"},
	{"Geomorphology", "Landforms and surface processes"},
	{"Hydrology", "Water systems"},
	{"Glaciology", "Ice and glaciers"},
	{"Soil Science", "Soils"},
	{"Oceanography", "Oceans"},
	{"Physical Oceanography", "Ocean physics"},
	{"Chemical Oceanography", "Ocean chemistry"},
	{"Biological Oceanography", "Marine ecosystems"},
	{"Meteorology", "Weather"},
	{"Climatology", "Climate systems"},
	{"Atmospheric Science", "Atmospheric processes"},
	{"Cryospheric Science", "Frozen Earth systems"},
	{"Planetary Science", "Planets and moons"},
	{"Astronomy", "Study of celestial objects"},
	{"Observational Astronomy", "Astronomy via observation"},
	{"Theoretical Astronomy", "Mathematical models of celestial systems"},
	{"Stellar Astronomy", "Stars"},
	{"Galactic Astronomy", "Galaxies"},
	{"Exoplanet Science", "Planets outside the solar system"},
	{"Solar Physics", "The Sun"},
	{"Space Physics", "Physical processes in space"},
	{"Heliophysics", "Sun–solar system interactions"},
	{"Cosmochemistry", "Chemical composition of the universe"},
	{"Materials Science", "Properties and design of materials"},
	{"Nanoscience", "Matter at nanometer scale"},
	{"Nanotechnology", "Engineering at nanoscale"},
	{"Environmental Science", "Earth systems and human interaction"},
	{"Cognitive Neuroscience", "Biological basis of cognition"},
	{"Chemical Physics", "Overlap of chemistry and physics"},
	{"Physical Biology", "Physical principles in biology"},
	{"Earth System Science", "Earth as an integrated system"},

	// MATH

	{"Mathematics", "Abstract study of quantity, structure, space, and change"},
	{"Mathematical Logic", "Formal reasoning and proof systems"},
	{"Propositional Logic", "Logic of propositions"},
	{"Predicate Logic", "Logic with quantifiers"},
	{"Model Theory", "Models of formal theories"},
	{"Proof Theory", "Structure of mathematical proofs"},
	{"Recursion Theory", "Computability and decidability"},
	{"Set Theory", "Study of sets and infinite structures"},
	{"Axiomatic Set Theory", "Formal axioms of set theory"},
	{"Category Theory", "Mathematical structures and mappings"},
	{"Type Theory", "Types as foundations of mathematics"},
	{"Foundations of Mathematics", "Philosophical and formal basis of math"},

	// === ALGEBRA ===
	{"Algebra", "Study of symbols and algebraic structures"},
	{"Elementary Algebra", "Basic algebraic operations"},
	{"Linear Algebra", "Vector spaces and linear maps"},
	{"Abstract Algebra", "General algebraic structures"},
	{"Group Theory", "Groups and symmetry"},
	{"Ring Theory", "Rings and algebraic systems"},
	{"Field Theory", "Fields and extensions"},
	{"Module Theory", "Generalization of vector spaces"},
	{"Algebraic Structures", "Semigroups, monoids, lattices"},
	{"Homological Algebra", "Algebraic structures via homology"},
	{"Universal Algebra", "Common structures of algebraic systems"},
	{"Lie Algebra", "Continuous symmetry algebras"},
	{"Commutative Algebra", "Commutative rings and ideals"},
	{"Noncommutative Algebra", "Noncommutative algebraic systems"},
	{"Algebraic K-Theory", "Algebraic invariants"},
	{"Representation Theory", "Representing algebraic structures via linear maps"},
	{"Algebraic Geometry", "Geometry defined by polynomial equations"},
	{"Arithmetic Geometry", "Algebraic geometry over number fields"},

	// === NUMBER THEORY ===
	{"Number Theory", "Properties of integers and numbers"},
	{"Elementary Number Theory", "Divisibility and primes"},
	{"Analytic Number Theory", "Number theory via analysis"},
	{"Algebraic Number Theory", "Number fields and algebraic integers"},
	{"Transcendental Number Theory", "Non-algebraic numbers"},
	{"Diophantine Geometry", "Polynomial equations over integers"},
	{"Computational Number Theory", "Algorithms for number theory"},
	{"p-adic Number Theory", "p-adic numbers and analysis"},
	{"Arithmetic Combinatorics", "Additive and multiplicative structures"},

	// === GEOMETRY ===
	{"Geometry", "Study of space and form"},
	{"Euclidean Geometry", "Classical geometry"},
	{"Non-Euclidean Geometry", "Geometry with modified axioms"},
	{"Differential Geometry", "Smooth manifolds and curvature"},
	{"Riemannian Geometry", "Metric and curvature structures"},
	{"Symplectic Geometry", "Geometry of phase space"},
	{"Algebraic Geometry", "Geometry of polynomial solutions"},
	{"Projective Geometry", "Geometry with points at infinity"},
	{"Affine Geometry", "Geometry without metric"},
	{"Discrete Geometry", "Combinatorial geometric structures"},
	{"Computational Geometry", "Algorithms for geometric problems"},
	{"Fractal Geometry", "Self-similar geometric objects"},
	{"Convex Geometry", "Convex sets and functions"},
	{"Topology", "Properties preserved under deformation"},
	{"Point-Set Topology", "General topological spaces"},
	{"Algebraic Topology", "Topological invariants"},
	{"Differential Topology", "Smooth structure of manifolds"},
	{"Geometric Topology", "Topology of manifolds"},

	// === ANALYSIS ===
	{"Mathematical Analysis", "Limits, continuity, and change"},
	{"Real Analysis", "Functions of real variables"},
	{"Complex Analysis", "Functions of complex variables"},
	{"Functional Analysis", "Infinite-dimensional vector spaces"},
	{"Harmonic Analysis", "Fourier and wave analysis"},
	{"Measure Theory", "Generalized notions of measure"},
	{"Integration Theory", "Theory of integration"},
	{"Operator Theory", "Linear operators"},
	{"Nonlinear Analysis", "Nonlinear systems"},
	{"Calculus of Variations", "Optimization of functionals"},
	{"Potential Theory", "Harmonic and potential functions"},
	{"Geometric Analysis", "Analysis using geometric methods"},

	// === DIFFERENTIAL EQUATIONS ===
	{"Differential Equations", "Equations involving derivatives"},
	{"Ordinary Differential Equations", "Single-variable differential equations"},
	{"Partial Differential Equations", "Multi-variable differential equations"},
	{"Dynamical Systems", "Evolution of systems over time"},
	{"Chaos Theory", "Sensitive dependence on initial conditions"},
	{"Integrable Systems", "Exactly solvable systems"},
	{"Stochastic Differential Equations", "Differential equations with randomness"},

	// === PROBABILITY & STATISTICS ===
	{"Probability Theory", "Mathematics of randomness"},
	{"Measure-Theoretic Probability", "Probability via measure theory"},
	{"Stochastic Processes", "Random processes over time"},
	{"Markov Processes", "Memoryless stochastic processes"},
	{"Martingale Theory", "Fair game processes"},
	{"Statistics", "Inference from data"},
	{"Mathematical Statistics", "Statistical theory"},
	{"Bayesian Statistics", "Probabilistic inference"},
	{"Statistical Learning Theory", "Mathematical basis of learning"},
	{"Information Theory", "Quantification of information"},
	{"Entropy Theory", "Information and disorder"},

	// === DISCRETE MATHEMATICS ===
	{"Discrete Mathematics", "Mathematics of discrete structures"},
	{"Combinatorics", "Counting and arrangement"},
	{"Graph Theory", "Graphs and networks"},
	{"Extremal Combinatorics", "Maximal and minimal structures"},
	{"Enumerative Combinatorics", "Counting methods"},
	{"Design Theory", "Combinatorial designs"},
	{"Finite Geometry", "Geometric structures over finite sets"},
	{"Matroid Theory", "Abstract independence structures"},
	{"Discrete Probability", "Probability on discrete spaces"},

	// === COMPUTATIONAL & APPLIED MATH ===
	{"Applied Mathematics", "Mathematics applied to real-world problems"},
	{"Numerical Analysis", "Approximation of mathematical problems"},
	{"Scientific Computing", "Computation for science and engineering"},
	{"Computational Mathematics", "Algorithmic mathematics"},
	{"Optimization", "Finding extrema"},
	{"Linear Programming", "Linear optimization"},
	{"Nonlinear Programming", "Nonlinear optimization"},
	{"Operations Research", "Optimization of systems"},
	{"Game Theory", "Strategic interaction"},
	{"Control Theory", "Control of dynamical systems"},
	{"Mathematical Modeling", "Modeling real systems"},
	{"Inverse Problems", "Recovering causes from effects"},

	// === INTERDISCIPLINARY & MODERN AREAS ===
	{"Mathematical Physics", "Mathematics of physical theories"},
	{"Quantum Mathematics", "Mathematical structures of quantum theory"},
	{"Financial Mathematics", "Mathematics of finance"},
	{"Actuarial Mathematics", "Risk and insurance mathematics"},
	{"Biomathematics", "Mathematics applied to biology"},
	{"Mathematical Chemistry", "Mathematical models in chemistry"},
	{"Mathematical Economics", "Formal economic theory"},
	{"Topological Data Analysis", "Topology applied to data"},
	{"Information Geometry", "Geometry of probability spaces"},
	{"Category-Theoretic Logic", "Logic via category theory"},
}
